---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    allow:
      # Only development dependencies can be updated due to the perculiar nature of fvtt-types.
      # Specifically the production dependencies of fvtt-types are all pinned to whatever version Foundry has.
      - dependency-type: development
    groups:
      everything:
        patterns:
          - "*"
    directory: "/"
    schedule:
      interval: "daily"
