name: checks
on:
  - push
  - pull_request
jobs:
  typecheck:
    name: type check code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        uses: jaid/action-npm-install@v1.2.1
      - name: run typescript error reporter
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
  lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        uses: jaid/action-npm-install@v1.2.1
      - name: run eslint
        uses: Krizzu/eslint-check-action@v1.1.0
        env:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          eslintFiles: 'types, index.d.ts'
          eslintConfig: .eslintrc.json
          eslintExt: 'ts'
