name: checks
on:
  - push
  - pull_request
jobs:
  typecheck:
    name: type check code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        uses: jaid/action-npm-install@v1.2.1
      - name: run typescript error reporter
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_TYPESCRIPT_ES: true
