name: checks
on:
  - push
  - pull_request
jobs:
  typecheck:
    name: type check code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        run: npm install
      - name: compile typescript
        run: tsc
  lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        run: npm install
      - name: run eslint
        run: npm run lint:ci
  test:
    name: test code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        run: npm install
      - name: execute tests
        run: npm test
