name: typecheck
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
jobs:
  tsc:
    name: type check code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: run typescript error reporter
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
